### ISSUE TITLE
chore: docker-compose.yml for tests

### ISSUE THREAD

**Issue by eujuliu** [eujuliu/test#2]
```yml
services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - project-network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: project-db
    restart: always
    command: [ "--replSet", "rs0", "--bind_ip_all", "--port", "27017" ]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30

  mongo-gui:
    image: mongo-express
    restart: always
    container_name: mongo-gui
    networks:
      - project-network
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/?directConnection=true&appName=mongosh+1.10.5

  redis:
    image: redis/redis-stack
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'

networks:
  project-network:
    driver: bridge

```
